// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYH4WSXpUviE0wSqhll-Vqq9jsATsV9OE',
    appId: '1:197046408067:web:da8b4c54c6be020e3c5cb6',
    messagingSenderId: '197046408067',
    projectId: 'cardi-care-63559',
    authDomain: 'cardi-care-63559.firebaseapp.com',
    storageBucket: 'cardi-care-63559.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDb9zm9LK09xPm3Vd0b4_OQkCSH2unpXU',
    appId: '1:197046408067:android:712dafec22d963133c5cb6',
    messagingSenderId: '197046408067',
    projectId: 'cardi-care-63559',
    storageBucket: 'cardi-care-63559.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgNmeiHEUATHqj-Oufndz2c5RC7vj49Zo',
    appId: '1:197046408067:ios:f0391add67eb28a33c5cb6',
    messagingSenderId: '197046408067',
    projectId: 'cardi-care-63559',
    storageBucket: 'cardi-care-63559.appspot.com',
    iosBundleId: 'com.example.cardiCare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgNmeiHEUATHqj-Oufndz2c5RC7vj49Zo',
    appId: '1:197046408067:ios:f0391add67eb28a33c5cb6',
    messagingSenderId: '197046408067',
    projectId: 'cardi-care-63559',
    storageBucket: 'cardi-care-63559.appspot.com',
    iosBundleId: 'com.example.cardiCare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYH4WSXpUviE0wSqhll-Vqq9jsATsV9OE',
    appId: '1:197046408067:web:850680faff3a2a993c5cb6',
    messagingSenderId: '197046408067',
    projectId: 'cardi-care-63559',
    authDomain: 'cardi-care-63559.firebaseapp.com',
    storageBucket: 'cardi-care-63559.appspot.com',
  );
}
